[catedral_nodes]
node-alfa ansible_host=10.0.0.1 ansible_user=arkhe
node-beta ansible_host=10.0.0.2 ansible_user=arkhe
node-gama ansible_host=10.0.0.3 ansible_user=arkhe

[catedral_nodes:vars]
ansible_python_interpreter=/arkhe/venv/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
