[package]
name = "catedral-hardware"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
async-trait.workspace = true
thiserror.workspace = true
serialport.workspace = true
reqwest.workspace = true
uuid.workspace = true
